// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzn-40vgfx7bCriVcvVUb4lR3OQPjb7Xg',
    appId: '1:997511987909:web:5553d9680ac027b0a126ac',
    messagingSenderId: '997511987909',
    projectId: 'tuitioni-1efa5',
    authDomain: 'tuitioni-1efa5.firebaseapp.com',
    storageBucket: 'tuitioni-1efa5.firebasestorage.app',
    measurementId: 'G-7FWF9M1F5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgGeeszfWi7RNKvH0uJw623E1oZQZBoOI',
    appId: '1:997511987909:android:7458047d5229669ca126ac',
    messagingSenderId: '997511987909',
    projectId: 'tuitioni-1efa5',
    storageBucket: 'tuitioni-1efa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt-bXGSKqxdE9r_aJeNSTDC00cJcPGVRM',
    appId: '1:997511987909:ios:3af5d7ad182c9098a126ac',
    messagingSenderId: '997511987909',
    projectId: 'tuitioni-1efa5',
    storageBucket: 'tuitioni-1efa5.firebasestorage.app',
    iosBundleId: 'com.example.adminTutorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt-bXGSKqxdE9r_aJeNSTDC00cJcPGVRM',
    appId: '1:997511987909:ios:3af5d7ad182c9098a126ac',
    messagingSenderId: '997511987909',
    projectId: 'tuitioni-1efa5',
    storageBucket: 'tuitioni-1efa5.firebasestorage.app',
    iosBundleId: 'com.example.adminTutorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzn-40vgfx7bCriVcvVUb4lR3OQPjb7Xg',
    appId: '1:997511987909:web:dd7b91c08e7bc2a6a126ac',
    messagingSenderId: '997511987909',
    projectId: 'tuitioni-1efa5',
    authDomain: 'tuitioni-1efa5.firebaseapp.com',
    storageBucket: 'tuitioni-1efa5.firebasestorage.app',
    measurementId: 'G-JDC6R0GH44',
  );

}